site_name: Inspector
docs_dir: .
site_dir: ../site
repo_url: https://github.com/StrangeRanger/inspector

theme:
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: blue
  features:
    #- navigation.tabs  # Disabled for this project
    - navigation.instant
    - navigation.sections
  icon:
    repo: fontawesome/brands/github

plugins:
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - search
  - same-dir

markdown_extensions:
  # Built in extensions
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - admonition
  - meta
  - footnotes
  # Extensions provide by pymdown
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed

nav:
  - Home: README.md
  - Features: docs/features.md
  - Limitations: docs/limitations.md
  - Dev Documentation: 
    - Dev Readme: docs/dev-docs/index.md
    - Doc 1: docs/dev-docs/doc-1.md
    - Doc 2: docs/dev-docs/doc-2.md
  - Changelog: CHANGELOG.md
  - License: LICENSE.md
