site_name: Inspector
site_description: Not sure, what thought I know it does something
repo_url: https://github.com/StrangeRanger/inspector
repo_name: StrangeRanger/inspector

theme:
  name: material
  palette:
    scheme: slate
    primary: blue
    accent: blue
  features:
    #- navigation.tabs  # Disabled for this project
    - navigation.instant
    - navigation.sections
  icon:
    repo: fontawesome/brands/github

plugins:
  - minify:
      minify_html: true
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - search

markdown_extensions:
  # Built in extensions
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - admonition
  - meta
  - footnotes
  # Extensions provide by pymdown  
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed

nav:
  - Home: index.md
  - Features: features.md
  - Limitations: limitations.md
  - Dev Documentation: 
    - Dev Readme: dev-docs/index.md
    - Doc 1: dev-docs/doc-1.md
    - Doc 2: dev-docs/doc-2.md
  - License: license.md
